# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr: none

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 12.x
  displayName: Install Node.js

- script: choco install azure-functions-core-tools-3 -y --params "'/x64'"
  displayName: choco install azure-functions-core-tools

- task: AzureCLI@2
  displayName: Build and publish azure-functions
  inputs:
    azureSubscription: Azure for Students(3e586571-9988-4808-8656-94d9d2bc0639)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      npm ci
      npm run build:production
      func azure functionapp publish CEN5035Spring2021DavidBruckProject --no-build --javascript --force
    workingDirectory: ./azure-functions

- task: AzureCLI@2
  displayName: Build and publish svelte-app
  inputs:
    azureSubscription: Azure for Students(3e586571-9988-4808-8656-94d9d2bc0639)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      npm ci
      npm run build
      az storage blob sync --account-name cen5035spring2021dbruck -c \$web -s public
    workingDirectory: ./svelte-app
