# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr: none

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 12.x
  displayName: Install Node.js

- script: choco install azure-functions-core-tools-3 -y --params "'/x64'"
  displayName: choco install azure-functions-core-tools

- script: |
    npm ci
    npm run build
  displayName: npm install and build svelte-app
  workingDirectory: ./svelte-app

- task: AzureCLI@2
  displayName: Build and publish azure-functions
  inputs:
    azureSubscription: Azure for Students(3e586571-9988-4808-8656-94d9d2bc0639)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      npm ci
      npm run build:production
      func azure functionapp publish CEN5035Spring2021DavidBruckProject --no-build --javascript --force
    workingDirectory: ./azure-functions

- task: AzureFileCopy@4
  displayName: Publish svelte-app
  inputs:
    SourcePath: $(Build.SourcesDirectory)/svelte-app/public/*
    azureSubscription: Azure for Students(3e586571-9988-4808-8656-94d9d2bc0639)
    Destination: AzureBlob
    storage: cen5035spring2021dbruck
    ContainerName: $web
