# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 15.x
  displayName: Install Node.js

- script: sudo apt-get install azure-functions-core-tools
  displayName: Install azure-functions-core-tools

- script: npm ci
  displayName: npm install root dependencies

- script: npm ci
  displayName: npm install svelte-app dependencies
  workingDirectory: ./svelte-app

- script: npm run validate
  displayName: validate svelte-app
  workingDirectory: ./svelte-app

- script: npm ci
  displayName: npm install azure-functions dependencies
  workingDirectory: ./azure-functions

- script: npm ci
  displayName: npm install svelte-app-tests dependencies
  workingDirectory: ./svelte-app-tests

- script: npm run lint-nofix
  displayName: lint

- script: npm test
  displayName: npm test
  workingDirectory: ./svelte-app-tests
